chore: hw08 is done
AlxBystrov/otusGo pull request #10
Opened 2023-12-24 10:45 UTC by AlxBystrov

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-24 12:40 UTC, ityulkanov requested changes
Оставил парочку комментариев, поможете разобраться?

2023-12-24 12:40 UTC, ityulkanov commented on hw08_envdir_tool/executor_test.go
> +	}
Вот тут тесткейс кмк не совсем репрезентативен. По идее мы же должны проверить что либо а) мы удаляем env переменную которая уже была добавлена посредством нашей envdir либо б) заменяем одно значение на другое, а тут мы по сути проверяем что у нас получилось запустить)))

2023-12-24 12:40 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +	executor.Env = os.Environ()
не нахожу где мы сливаем параметры что были изначально с нашими новыми параметрами. 
Т.е. предположим у нас было назначено DB_PATH=/db/path, мы с помощью утилиты хотим поменять на DB_PATH=/db/newpath, если у нас заранее не слиты те что были с новыми, то замены не случится

2023-12-25 06:22 UTC, AlxBystrov commented on hw08_envdir_tool/executor_test.go
> +	}
Согласен. Немного дополнил структуру и добавил тест-кейсов. По кейсам показал установку значения, его изменение и unset.

2023-12-25 06:26 UTC, AlxBystrov commented on hw08_envdir_tool/executor.go
> +	executor.Env = os.Environ()
Если не ошибаюсь, природа env такова, что используется последнее установленное значение. В цикле с 10 по 16 строку я устанавливаю нужные значения и удаляю, те, что нужно почистить. Не уверен, но есть ли смысл читать то, что будет изменено? В тест-кейсах добавил случай с изменением значения, чтобы показать, что так работает. Опять же, если правильно понял вопрос.

2023-12-25 09:55 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +	executor.Env = os.Environ()
Да, пожалуй так, последнее значение перетирает остальные. Но кмк остальные значения всё же стоит затянуть в наш внутренний энв всё же.

2023-12-25 11:35 UTC, AlxBystrov commented on hw08_envdir_tool/executor.go
> +	executor.Env = os.Environ()
А [os.Environ()](https://pkg.go.dev/os#Environ) на 19 строке как раз подтягиевает всё. При выполнении скрипта для команды env видны все переменные окружения системы.

2023-12-25 12:01 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +	executor.Env = os.Environ()
Ок, понял. Тогда вопросов больше  нет

2023-12-25 12:01 UTC, ityulkanov approved these changes

2023-12-25 12:39 UTC, merged